### ISSUE TITLE
iam_user advanced example for password_reset_required - throws error

### ISSUE THREAD

**Issue by Constantin07** [k1LoW/awspec#174]
Hi,

It seems that the advanced example given here https://github.com/k1LoW/awspec/blob/master/doc/resource_types.md#iam_user doesn't work properly.

```
describe iam_user('every_user') do
    it { should exist }
    ...
    its('resource.login_profile.password_reset_required') { should eq false }
end
```

error:
```
iam_user 'every_user'
  should exist
  ....
  resource.login_profile.password_reset_required
    example at ./spec/infra_spec.rb:153 (FAILED - 1)

Failures:

  1) iam_user 'every_user' resource.login_profile.password_reset_required
     Failure/Error: its('resource.login_profile.password_reset_required') { should eq false }

     Awspec::BlackListForwardable::CalledMethodInBlackList:
       Method call :password_reset_required is black-listed
     # /usr/local/rvm/gems/ruby-2.1.8/gems/awspec-0.49.0/lib/awspec/resource_reader.rb:8:in `method_missing_via_black_list'
     # /usr/local/rvm/gems/ruby-2.1.8/gems/awspec-0.49.0/lib/awspec/resource_reader.rb:43:in `method_missing'
     # ./spec/infra_spec.rb:153:in `block (2 levels) in <top (required)>'

Finished in 2.6 seconds (files took 3.62 seconds to load)
96 examples, 1 failure

Failed examples:

rspec ./spec/infra_spec.rb:153 # iam_user 'every_user' resource.login_profile.password_reset_required
```

and here is the result from AWS CLI:
```
$ aws iam get-login-profile --user-name every_user
{
    "LoginProfile": {
        "UserName": "every_user",
        "CreateDate": "2016-05-24T12:25:00Z",
        "PasswordResetRequired": false
    }
}
```

Any thoughts?

Regards,
Constantin

**Comment by k1LoW** [comment]
Hi @Constantin07 

Key name blacklisted( `Awspec::BlackListForwardable::CalledMethodInBlackList:`. see https://github.com/k1LoW/awspec/blob/master/lib/awspec/resource_reader.rb#L20)

## Why blacklist

awspec should not be able to break resources.

---

I want to wait your nice pull request :)

**Comment by Constantin07** [comment]
Thanks @k1LoW for guidance. Raised PR #180 but I get another error which I believe is something wrong with code in another place:

```
Failures:

  1) iam_user 'every_user' login_profile.password_reset_required
     Failure/Error: its('login_profile.password_reset_required') { should eq false }

     Aws::IAM::Errors::NoSuchEntity:
       The user with name AIDAIOOCQKTUGI6QJLGH2 cannot be found.
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-core-2.5.6/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-core-2.5.6/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-core-2.5.6/lib/seahorse/client/plugins/response_target.rb:21:in `call'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-core-2.5.6/lib/seahorse/client/request.rb:70:in `send_request'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-core-2.5.6/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.5.6/lib/aws-sdk-resources/request.rb:24:in `call'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.5.6/lib/aws-sdk-resources/operations.rb:41:in `call'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.5.6/lib/aws-sdk-resources/operations.rb:61:in `call'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.5.6/lib/aws-sdk-resources/resource.rb:147:in `load'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.5.6/lib/aws-sdk-resources/resource.rb:120:in `data'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/aws-sdk-resources-2.5.6/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/awspec-0.52.1/lib/awspec/resource_reader.rb:9:in `method_missing_via_black_list'
     # /usr/local/rvm/gems/ruby-2.3.0/gems/awspec-0.52.1/lib/awspec/resource_reader.rb:50:in `method_missing'
     # ./spec/infra_spec.rb:158:in `block (2 levels) in <top (required)>'

Finished in 3.68 seconds (files took 3.97 seconds to load)
102 examples, 1 failure

Failed examples:

rspec ./spec/infra_spec.rb:158 # iam_user 'every_user' login_profile.password_reset_required
```

It turns out it tries somewhere in the code to find the user name but supplies instead actually user id which obviously fails as in AWS these are different attributes of IAM user.
 
From the above trace it's difficult to identify where it fails ... Could you please help?

Regards,
Constantin

**Comment by k1LoW** [comment]
Hi @Constantin07.
Fix `Aws::IAM::Errors::NoSuchEntity:` error at awspec v0.52.4.

**Comment by k1LoW** [comment]
@Constantin07 
Thank you for your nice report!

**Comment by Constantin07** [comment]
You help is much appreciated too. :-)
