### ISSUE TITLE
iam_role example in documentation raises "Method call :attached_policies is black-listed"

### ISSUE THREAD

**Issue by nhinds** [k1LoW/awspec#196]
The `iam_role` resource documentation suggests using the following syntax:

```
describe iam_role('my-iam-role') do
  its('attached_policies.count') { should eq 5 }
end
```

Doing so results in the following error being raised:

```
Awspec::BlackListForwardable::CalledMethodInBlackList:
  Method call :attached_policies is black-listed
# .../gems/awspec-0.60.0/lib/awspec/resource_reader.rb:9:in `method_missing_via_black_list'
# .../gems/awspec-0.60.0/lib/awspec/type/base.rb:62:in `method_missing'
```

The alternate suggested form ("resource.attached_policies.count") gives the same error.

**Comment by k1LoW** [comment]
Thank you for good issue. now fixing.
