### ISSUE TITLE
Security group `be_opened` matches when it should not for e.g. 0.0.0.0/0 or 0.0.0.0/32

### ISSUE THREAD

**Issue by nhinds** [k1LoW/awspec#338]
I've got a security group which should not have egress allowed, and so I have the following test which asserts that it does not have open access to the internet:

```
    describe security_group(sg) do
      context 'should not allow egress TCP and UDP for 0.0.0.0/0' do
        its(:outbound) { should_not be_opened('0-65535').protocol('tcp').for('0.0.0.0/0') }
        its(:outbound) { should_not be_opened('0-65535').protocol('udp').for('0.0.0.0/0') }
      end
    end
```

My security group's egress rules include a dummy rule for `0.0.0.0/32` which ensures the default security group egress behaviour (access to everything) is not applied:
```
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1", 
                    "PrefixListIds": [], 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/32"
                        }
                    ], 
                    "UserIdGroupPairs": [], 
                    "Ipv6Ranges": []
                }
            ]
```

Previously, in awspec 0.73.1, the tests worked fine. My security group does not have an egress rule for `0.0.0.0/0` for TCP or UDP, so `be_opened('0-65535').protocol('tcp').for('0.0.0.0/0')` did not match.

Today I updated to awspec 0.88.1 and these tests started failing. The message does not really explain why:
```
Failures:

  1) security_group 'sg-12345678' should not allow egress TCP and UDP for 0.0.0.0/0 outbound should not be opened "0-65535" protocol "tcp" for "0.0.0.0/0"
     Failure/Error: its(:outbound) { should_not be_opened('0-65535').protocol('tcp').for('0.0.0.0/0') }
       expected security_group 'sg-12345678' not to be opened "0-65535" protocol "tcp" for "0.0.0.0/0"
     # my_spec.rb:12:in `block (3 levels) in <top (required)>'

  2) security_group 'sg-12345678' should not allow egress TCP and UDP for 0.0.0.0/0 outbound should not be opened "0-65535" protocol "udp" for "0.0.0.0/0"
     Failure/Error: its(:outbound) { should_not be_opened('0-65535').protocol('udp').for('0.0.0.0/0') }
       expected security_group 'sg-12345678' not to be opened "0-65535" protocol "udp" for "0.0.0.0/0"
     # my_spec.rb:13:in `block (3 levels) in <top (required)>'
```

This could be related to #332, since it seemed to change how CIDR matching worked.

**Comment by k1LoW** [comment]
@nhinds Thank you for your report!!! I'll check it.

**Comment by k1LoW** [comment]
I check `IPAddr#include?`

```console
~ > pry                                                                                                                                                                       
[1] pry(main)> require 'ipaddr'
                               => true
[2] pry(main)> n = IPAddr.new('0.0.0.0/0')
                                          => #<IPAddr: IPv4:0.0.0.0/0.0.0.0>
[3] pry(main)> t = IPAddr.new('0.0.0.0/32')
                                           => #<IPAddr: IPv4:0.0.0.0/255.255.255.255>
[4] pry(main)> n.include?(t)
                            => true
[5] pry(main)> t.include?(n)
                            => true
```

**Comment by k1LoW** [comment]
I check ipaddress.gem

```
> pry
[1] pry(main)> require 'ipaddress'
                                  => true
[2] pry(main)> n = IPAddress::IPv4.new('0.0.0.0/0')
                                                   => #<IPAddress::IPv4:0x007ff3c400a220 @address="0.0.0.0", @octets=[0, 0, 0, 0], @prefix=0, @u32=0>
[3] pry(main)> t = IPAddress::IPv4.new('0.0.0.0/32')
                                                    => #<IPAddress::IPv4:0x007ff3c3034a58 @address="0.0.0.0", @octets=[0, 0, 0, 0], @prefix=32, @u32=0>
[4] pry(main)> n.include?(t)
                            => true
[5] pry(main)> t.include?(n)
                            => false
```

**Comment by nhinds** [comment]
It looks like the `IPAddr` library is not suitable for comparing if one CIDR block contains another CIDR block. Its `.include?` method assumes that it's being given a single address as its argument, not a network/CIDR block.

Or, put another way: as long as the CIDR blocks have the same dotted numbers, `IPAddr.include?` returns true regardless of their masks.

This includes CIDR blocks that aren't just `0.0.0.0`:

```
2.4.1 :024 > IPAddr.new('10.5.0.0/24').include? '10.5.0.0/16'
 => true 
2.4.1 :025 > IPAddr.new('10.5.0.0/16').include? '10.5.0.0/24'
 => true 
```

**Comment by k1LoW** [comment]
> It looks like the IPAddr library is not suitable for comparing if one CIDR block contains another CIDR block.

Yes. I'll change `IPAddr`. Thank you.
