### ISSUE TITLE
"prefix" of s3_bucket have_lifecycle_rule does not work

### ISSUE THREAD

**Issue by oosumi** [k1LoW/awspec#365]
- awspec v1.5.1

It seems that 'nil' will be returned by AWS side change.
Instead we will use filter.prefix.
However, I do not know if it has changed in all environments.

- https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Types/LifecycleRule.html#prefix-instance_method

> This is deprecated; use Filter instead.

**Comment by htnosm** [comment]
The above pull request is a draft.
As a separate issue from the above,
'awspec' abends abnormally if there is tag setting in filter of lifecycle.

```
`child_frame': NotImplementedError (NotImplementedError)
```

**Comment by htnosm** [comment]
It is a failure case by tag setting.

# Error Pattern

## S3 lifecycle-configuration

Set Filter Tag.

```
$ aws s3api get-bucket-lifecycle-configuration --bucket check-dummy-bucket --query 'Rules[]'
[
    {
        "Filter": {
            "And": {
                "Prefix": "",
                "Tags": [
                    {
                        "Value": "test",
                        "Key": "tagtest"
                    }
                ]
            }
        },
        "Status": "Enabled",
        "Expiration": {
            "Days": 365
        },
        "ID": "test-lifecycle"
    }
]
```

## spec

```
$ cat spec/s3_bucket_spec.rb
require 'awspec'

describe s3_bucket('check-dummy-bucket') do
  it { should exist }
  it do
    should have_lifecycle_rule(
      id: 'test-lifecycle',
      expiration: { days: 365 },
      transitions: [],
      status: 'Enabled'
    )
  end
end
```

## rake result

```
Failures:

  1) s3_bucket 'check-dummy-bucket' should have lifecycle rule {:id=>"test-lifecycle", :expiration=>{:days=>365}, :transitions=>[], :status=>"Enabled"}
     Failure/Error:
       should have_lifecycle_rule(
         id: 'test-lifecycle',
         expiration: { days: 365 },
         transitions: [],
         status: 'Enabled'
       )

     NotImplementedError:
       NotImplementedError
     # ./spec/s3_bucket_spec.rb:6:in `block (2 levels) in <top (required)>'

Finished in 0.48581 seconds (files took 1.76 seconds to load)
```

## generate result

```
$ awspec generate s3_bucket check-dummy-bucket
/home/ec2-user/.rbenv/versions/2.2.10/lib/ruby/gems/2.2.0/gems/aws-sdk-core-3.19.0/lib/aws-sdk-core/xml/parser/frame.rb:148:in `child_frame': NotImplementedError (NotImplementedError)
```

# Normal Pattern

## S3 lifecycle-configuration

Set Filter Prefix
or
Not set tag and prefix

```
$ aws s3api get-bucket-lifecycle-configuration --bucket check-dummy-bucket --query 'Rules[]'
[
    {
        "Filter": {
            "Prefix": ""
        },
        "Status": "Enabled",
        "Expiration": {
            "Days": 365
        },
        "ID": "test-lifecycle"
    }
]
$ aws s3api get-bucket-lifecycle-configuration --bucket check-dummy-bucket --query 'Rules[]'
[
    {
        "Filter": {
            "Prefix": "logs/"
        },
        "Status": "Enabled",
        "Expiration": {
            "Days": 365
        },
        "ID": "test-lifecycle"
    }
]
```

**Comment by inokappa** [comment]
@htnosm 

Thanks for reporting this problem.
it’s a bug... 🙇 
I'll fix it.

**Comment by inokappa** [comment]
I confirmed `NotImplementedError` exception in aws-sdk-s3 v1.9.1 (+ aws-sdk-core v1.9.0)... 😱 

```
$ bundle exec pry
[1] pry(main)> require 'pp'
=> false
[2] pry(main)> require 'aws-sdk-s3'
=> true
[3] pry(main)> s3 = Aws::S3::Client.new(region: 'ap-northeast-1', profile: 'xxxxxxxxxxxx')
=> #<Aws::S3::Client>
[4] pry(main)> bcl = s3.get_bucket_lifecycle_configuration(bucket: 'oreno-bucket')
NotImplementedError: NotImplementedError
```

**Comment by inokappa** [comment]
I submitted an issue to aws-sdk-core as follows.

* https://github.com/aws/aws-sdk-ruby/issues/1764

**Comment by htnosm** [comment]
@inokappa 
Thank you for support.
I confirmed that it can be executed without error after upgrading SDK.

**Comment by inokappa** [comment]
@oosumi 

Thank you for your report.
I will close this issue.

Thank you.
