### ISSUE TITLE
rds resource should have_tag fails with 'method_missing'

### ISSUE THREAD

**Issue by metmajer** [k1LoW/awspec#376]
Hi there, and thanks for this awesome library!

I am running the following code in my `default_spec.rb`:

```
require 'awspec'
describe rds('aws-rds-1234567890') do
  it { should have_tag('Very-Important-Tag').value("some-very-important-value") }
end
```

Executing this code with rspec yields the following error:

```
  1) Blueprint rds 'aws-rds-1234567890' should have tag "Very-Important-Tag"
     Failure/Error: it { should have_tag('Very-Important-Tag').value("some-very-important-value") }

     ArgumentError:
       wrong number of arguments (given 3, expected 1)
     # ./vendor/bundle/ruby/2.3.0/gems/awspec-0.37.7/lib/awspec/type/base.rb:44:in `method_missing'
     # ./vendor/bundle/ruby/2.3.0/gems/awspec-0.37.7/lib/awspec/matcher/have_tag.rb:3:in `block (2 levels) in <top (required)>'
     # ./test/integration/default/default_spec.rb:13:in `block (3 levels) in <top (required)>'
```

Thanks for your insights!

Cheers, Martin

**Comment by nichtraunzer** [comment]
+1

**Comment by metmajer** [comment]
Surprised about how `awspec-0.37.7` came in as a dependency. I've changed the entry in my `Gemfile` to point to the latest version and as expected, the issue resolved.

```
source 'https://rubygems.org'
gem 'awspec', '~> 1.7.0'
```
