### ISSUE TITLE
some s3 tests failing...?

### ISSUE THREAD

**Issue by tony-kerz** [k1LoW/awspec#379]
* spec *
```
require 'awspec'

describe s3_bucket('tf-aws-s3-log-test') do
  it { should exist }
  it { should have_versioning_enabled }
  it { should have_tag('Terraform').value('true') }
  it { should have_tag('Tag1').value('val-1') }
  it { should have_tag('Tag2').value('val-2') }
  it { should have_acl_grant(grantee: 'http://acs.amazonaws.com/groups/s3/LogDelivery', permission: 'WRITE') }
  it { should have_acl_grant(grantee: 'http://acs.amazonaws.com/groups/s3/LogDelivery', permission: 'READ_ACP') }
end
```
* aws console for s3 bucket *
![screen shot 2018-08-01 at 7 13 34 pm](https://user-images.githubusercontent.com/1223231/43553864-2253c65c-95bf-11e8-873c-070e6925365d.png)

* output *
```
 ~/g/tf-aws-s3-log   tk/inspec  test/rspec  bundle exec rspec                               Wed Aug  1 19:11:07 2018

s3_bucket 'tf-aws-s3-log-test'
  should exist
  should have versioning enabled (FAILED - 1)
  should have tag "Terraform" (FAILED - 2)
  should have tag "Tag1" (FAILED - 3)
  should have tag "Tag2" (FAILED - 4)
  should have acl grant {:grantee=>"http://acs.amazonaws.com/groups/s3/LogDelivery", :permission=>"WRITE"}
  should have acl grant {:grantee=>"http://acs.amazonaws.com/groups/s3/LogDelivery", :permission=>"READ_ACP"}

Failures:

  1) s3_bucket 'tf-aws-s3-log-test' should have versioning enabled
     Failure/Error: it { should have_versioning_enabled }
       expected s3_bucket 'tf-aws-s3-log-test' to respond to `has_versioning_enabled?`
     # ./spec/main_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) s3_bucket 'tf-aws-s3-log-test' should have tag "Terraform"
     Failure/Error: it { should have_tag('Terraform').value('true') }

     ArgumentError:
       wrong number of arguments (given 3, expected 1)
     # ./spec/main_spec.rb:6:in `block (2 levels) in <top (required)>'

  3) s3_bucket 'tf-aws-s3-log-test' should have tag "Tag1"
     Failure/Error: it { should have_tag('Tag1').value('val-1') }

     ArgumentError:
       wrong number of arguments (given 3, expected 1)
     # ./spec/main_spec.rb:8:in `block (2 levels) in <top (required)>'

  4) s3_bucket 'tf-aws-s3-log-test' should have tag "Tag2"
     Failure/Error: it { should have_tag('Tag2').value('val-2') }

     ArgumentError:
       wrong number of arguments (given 3, expected 1)
     # ./spec/main_spec.rb:9:in `block (2 levels) in <top (required)>'

Finished in 0.24676 seconds (files took 1.67 seconds to load)
7 examples, 4 failures

Failed examples:

rspec ./spec/main_spec.rb:5 # s3_bucket 'tf-aws-s3-log-test' should have versioning enabled
rspec ./spec/main_spec.rb:6 # s3_bucket 'tf-aws-s3-log-test' should have tag "Terraform"
rspec ./spec/main_spec.rb:8 # s3_bucket 'tf-aws-s3-log-test' should have tag "Tag1"
rspec ./spec/main_spec.rb:9 # s3_bucket 'tf-aws-s3-log-test' should have tag "Tag2"
```

* Gemfile *
```
source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "awspec", "~> 0.37.7"
```

* gem list *
```
 !  ~/g/tf-aws-s3-log   tk/inspec *  test/rspec  bundle exec gem list             1592ms  Wed Aug  1 19:23:03 2018

*** LOCAL GEMS ***

activesupport (5.2.0)
aws-sdk (2.2.37)
aws-sdk-core (2.2.37)
aws-sdk-resources (2.2.37)
aws_config (0.0.4)
awsecrets (1.3.0)
awspec (0.37.8)
bundler (1.16.3)
concurrent-ruby (1.0.5)
diff-lcs (1.3)
i18n (1.0.1)
jmespath (1.4.0)
minitest (5.11.3)
rspec (3.7.0)
rspec-core (3.7.1)
rspec-expectations (3.7.0)
rspec-its (1.2.0)
rspec-mocks (3.7.0)
rspec-support (3.7.1)
term-ansicolor (1.6.0)
thor (0.20.0)
thread_safe (0.3.6)
tins (1.16.3)
tzinfo (1.2.5)
```

**Comment by inokappa** [comment]
Hi, @tony-kerz 

Thank you for your report.
I checked it.

It worked normally in my environment.
Please use awspec version 1.8.0 ;-)

* S3 Options

```sh
$ aws s3api get-bucket-tagging --bucket=awspec-debug-bucket
{
    "TagSet": [
        {
            "Key": "Tag1",
            "Value": "val-1"
        },
        {
            "Key": "Terraform",
            "Value": "true"
        },
        {
            "Key": "CreateDate",
            "Value": "2018-08-081T23:05:15Z"
        },
        {
            "Key": "Tag2",
            "Value": "val-2"
        }
    ]
}
$ aws s3api get-bucket-versioning --bucket=awspec-debug-bucket
{
    "Status": "Enabled"
}
$ aws s3api get-bucket-acl --bucket=awspec-debug-bucket
{
... snip ...
        {
            "Grantee": {
                "Type": "Group",
                "URI": "http://acs.amazonaws.com/groups/s3/LogDelivery"
            },
            "Permission": "WRITE"
        },
        {
            "Grantee": {
                "Type": "Group",
                "URI": "http://acs.amazonaws.com/groups/s3/LogDelivery"
            },
            "Permission": "READ_ACP"
        }
    ]
}
```

* awspec version

```sh
$ bundle exec gem list | grep awspec
awspec (1.8.0)
```

* spec

```ruby
require 'awspec'

describe s3_bucket('awspec-debug-bucket') do
  it { should exist }
  it { should have_versioning_enabled }
  it { should have_tag('Terraform').value('true') }
  it { should have_tag('Tag1').value('val-1') }
  it { should have_tag('Tag2').value('val-2') }
  it { should have_acl_grant(grantee: 'http://acs.amazonaws.com/groups/s3/LogDelivery', permission: 'WRITE') }
  it { should have_acl_grant(grantee: 'http://acs.amazonaws.com/groups/s3/LogDelivery', permission: 'READ_ACP') }
end
```

* result

```sh
s3_bucket 'awspec-debug-bucket'
  should exist
  should have versioning enabled
  should have tag "Terraform"
  should have tag "Tag1"
  should have tag "Tag2"
  should have acl grant {:grantee=>"http://acs.amazonaws.com/groups/s3/LogDelivery", :permission=>"WRITE"}
  should have acl grant {:grantee=>"http://acs.amazonaws.com/groups/s3/LogDelivery", :permission=>"READ_ACP"}

Finished in 1.98 seconds (files took 2.69 seconds to load)
7 examples, 0 failures
```

Regards.

Yohei.

**Comment by tony-kerz** [comment]
thanks yohei, version `1.8.0` worked great!

not clear to me how i got stuck with that old `0.38.x` version, i didn't call it out explicitly.

i'm just dusting off my local ruby environment after a long hiatus, so i'm guessing maybe i installed `awspec` while i was pointing to an old version of ruby, and it somehow got cached in there.

after pointing `rbenv` to `2.5.1`, reinitializing with `gem uninstall -aIx`, and `bundle add awspec` it grabs `1.8.0` as expected 👍 

thanks again, really appreciate the assist! take care...

**Comment by tony-kerz** [comment]
on a related note, i have two questions around the tag assertions:

1. can i check for the existence of a tag without checking the tag value? 
    ```
    it { should have_tag('CreationDate') }
    ```
    > the above is returning a failure...
1. is it possible to check the value of a tag against a regular expression, something like below?
    ```
    it { should have_tag('CreationDate').value(/regex-for-date-here/) }
    ```

> let me know if u prefer questions like this in stack-overflow or gitter or something 👍
