### ISSUE TITLE
ArgumentError exception "unknown operation :find_sns_topic"

### ISSUE THREAD

**Issue by glasswalk3r** [k1LoW/awspec#401]
Hi,

I'm trying to extend awspec by adding SNS verifications for it. I'm following the procedures described at
https://github.com/k1LoW/awspec/blob/master/doc/contributing.md for that.

I added a Awspec::Helper::Finder::SNSTopic module, with the following method:

```
      def find_sns_topic(topic_name)
        #response = sns_client.get_topic_attributes({ topic_arn: topic_name })
        "gfvtyf"
      end
```

And then:

```
module Awspec::Type
  class SnsTopic < ResourceBase
    def resource_via_client
      @resource_via_client ||= find_sns_topic(@topic_name)
    end

    def id
      # A SNS Topic doesn't have an ID...
      @id ||= resource_via_client if resource_via_client
    end
  end
end
```

If I run this specific test, everything "works":

```
[myself@localhost awspec]$ bundle exec rspec ./spec/type/sns_topic_spec.rb 
.

Finished in 0.00479 seconds (files took 1.88 seconds to load)
1 example, 0 failures
```

As soon as uncomment the line `#response = sns_client.get_topic_attributes({ topic_arn: topic_name })` from `find_sns_topic` I got an exception:

```
[myself@localhost awspec]$ bundle exec rspec ./spec/type/sns_topic_spec.rb 
F

Failures:

  1) sns_topic 'my-sns' should exist
     Failure/Error: Awspec::Helper::ClientWrap.new(client.new(CLIENT_OPTIONS))
     
     ArgumentError:
       unknown operation :find_sns_topic
     # ./lib/awspec/helper/finder.rb:144:in `block (2 levels) in <module:Finder>'
     # ./lib/awspec/helper/finder/sns_topic.rb:47:in `find_sns_topic'
     # ./lib/awspec/type/sns_topic.rb:4:in `resource_via_client'
     # ./lib/awspec/type/sns_topic.rb:9:in `id'
     # ./lib/awspec/type/resource_base.rb:11:in `exists?'
     # ./spec/type/sns_topic_spec.rb:5:in `block (2 levels) in <top (required)>'

Finished in 0.00721 seconds (files took 1.78 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/type/sns_topic_spec.rb:5 # sns_topic 'my-sns' should exist
```

This message is really confusing because it leads that the function cannot be found (and I did spent time looking over it), so this might be an issue by itself.

Of course, I'm also looking for a way to fix the bug introduced with `find_sns_topic`: there is no way I can use the `sns_client` as supposed to, even thought it is following the same declarations as for other resources:

```
[myself@localhost awspec]$ ack dynamodb_client
lib/awspec/helper/finder/dynamodb.rb
5:        resource = dynamodb_client.describe_table({ table_name: id }).table

lib/awspec/helper/finder.rb
123:      dynamodb_client: Aws::DynamoDB::Client,
[myself@localhost awspec]$ ack sns_client
lib/awspec/helper/finder/sns_topic.rb
44:        #wanted = "arn:aws:sns:#{sns_client.config.region}:#{account}:#{topic_name}"
47:        #response = sns_client.get_topic_attributes({ topic_arn: wanted })

lib/awspec/helper/finder.rb
132:      sns_client: Aws::SNS::Client
[myself@localhost awspec]$
```

What I am missing here?

Thanks!

**Comment by glasswalk3r** [comment]
At the end, I was able to implement `find_sns_topic` method successfully:

```ruby
module Awspec::Helper
  module Finder
    module SNSTopic
      class SnsTopic
        # to make testing results easier to the eyes instead of using Rspec
        # include matcher for hashes
        attr_reader :policy, :owner, :pending_subscriptions, :topic_arn, :effective_delivery_policy,
                    :display_name, :confirmed_subscriptions, :deleted_subscriptions, :name

        def initialize(attribs)
          @policy = attribs['Policy']
          @owner = attribs['Owner']
          @pending_subscriptions = attribs['SubscriptionsPending'].to_i
          @topic_arn = attribs['TopicArn']
          @effective_delivery_policy = attribs['EffectiveDeliveryPolicy']
          @display_name = attribs['DisplayName']
          @confirmed_subscriptions = attribs['SubscriptionsConfirmed'].to_i
          @deleted_subscriptions = attribs['SubscriptionsDeleted'].to_i
          @name = attribs['TopicArn'].split(':')[-1]
        end

        def to_s
          output = ["SnsTopic: #{self.name}"]
          self.instance_variables.each do |attrib|
            tmp = attrib.to_s.sub('@', '')
            output << "  #{tmp} = #{self.send(tmp)}"
          end
          output.join("\n")
        end
      end

      def find_sns_topic(topic_arn)
        response = sns_client.get_topic_attributes({ topic_arn: topic_arn })
        SnsTopic.new(response.attributes)
      end
```

I think we can close this issue for now.
