### ISSUE TITLE
NoMethodError exception when testing a missing IAM policy

### ISSUE THREAD

**Issue by glasswalk3r** [k1LoW/awspec#421]
Let's consider a non-existent `Foobar_S3` to be tested:

```ruby
iam_user 'foobar'
  should have iam policy "Foobar_S3" (FAILED - 7)

Failures:

  1) iam_policy 'Foobar_S3' should exist
     Failure/Error: it { should exist }
       expected iam_policy 'Foobar_S3' to exist
     # ./spec/policies_spec.rb:15:in `block (3 levels) in <top (required)>'

  2) iam_policy 'Foobar_S3' should be attachable
     Failure/Error: it { should be_attachable }
     
     NoMethodError:
       undefined method `is_attachable' for nil:NilClass
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/type/iam_policy.rb:12:in `attachable?'
     # ./spec/policies_spec.rb:16:in `block (3 levels) in <top (required)>'

  3) iam_policy 'Foobar_S3' should be attached to user "foobar"
     Failure/Error: it { should     be_attached_to_user(foobar_user) }
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/helper/finder/iam.rb:73:in `select_attached_entities'
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/helper/finder/iam.rb:77:in `select_attached_users'
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/type/iam_policy.rb:16:in `attached_to_user?'
     # ./spec/policies_spec.rb:18:in `block (3 levels) in <top (required)>'

  4) iam_policy 'Foobar_S3' should not be attached to group
     Failure/Error: it { should_not be_attached_to_group }
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/helper/finder/iam.rb:73:in `select_attached_entities'
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/helper/finder/iam.rb:82:in `select_attached_groups'
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/type/iam_policy.rb:29:in `attached_to_group?'
     # ./spec/policies_spec.rb:19:in `block (3 levels) in <top (required)>'

  5) iam_policy 'Foobar_S3' should not be attached to role
     Failure/Error: it { should_not be_attached_to_role }
     
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/helper/finder/iam.rb:73:in `select_attached_entities'
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/helper/finder/iam.rb:87:in `select_attached_roles'
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/type/iam_policy.rb:42:in `attached_to_role?'
     # ./spec/policies_spec.rb:20:in `block (3 levels) in <top (required)>'

  6) iam_policy 'Foobar_S3' attachment_count 
     Failure/Error: its(:attachment_count) { should eq 1 }
     
     NoMethodError:
       undefined method `attachment_count' for iam_policy 'Foobar_S3':Awspec::Type::IamPolicy
       Did you mean?  attached_to_user?
     # ./vendor/bundle/ruby/2.4.0/gems/awspec-1.12.1/lib/awspec/type/base.rb:42:in `method_missing'
     # ./spec/policies_spec.rb:17:in `block (3 levels) in <top (required)>'

  7) iam_user 'foobar' should have iam policy "Foobar_S3"
     Failure/Error: it { should have_iam_policy('Foobar_S3') }
       expected #has_iam_policy?("Foobar_S3") to return true, got false
     # ./spec/user_spec.rb:9:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 3.6 seconds (files took 7.97 seconds to load)
97 examples, 7 failures

Failed examples:

rspec ./spec/policies_spec.rb[1:1] # iam_policy 'Foobar_S3' should exist
rspec ./spec/policies_spec.rb[1:2] # iam_policy 'Foobar_S3' should be attachable
rspec ./spec/policies_spec.rb[1:4] # iam_policy 'Foobar_S3' should be attached to user "foobar"
rspec ./spec/policies_spec.rb[1:5] # iam_policy 'Foobar_S3' should not be attached to group
rspec ./spec/policies_spec.rb[1:6] # iam_policy 'Foobar_S3' should not be attached to role
rspec ./spec/policies_spec.rb[1:3:1] # iam_policy 'Foobar_S3' attachment_count 
rspec ./spec/user_spec.rb:9 # iam_user 'foobar' should have iam policy "Foobar_S3"

```
Of course the test is expected to fail, since the policy doesn't exist. But the exceptions raised should be something more substantial then `NoMethodError` since a object cannot be instantiated from a missing policy (generating a `nil:NilClass`).

In that case it seems the implementation lacks basic validation to raise an exception if the policy cannot be located at all.

**Comment by glasswalk3r** [comment]
Just created a PR for this. It fixes by adding delegation to the returned object from AWS SDK, but probably is it not the best implementation it could help and I request help to check on that.
I explicit added calls to a new private method that will generate an exception if the respective AWS SDK object instance is not available. That probably should be implemented with `method_missing`, but I'm not sure if I should implement that on the `Awspec::Type::IAMPolicy` itself or the parent class, since it could break all other types.
Also, I'm not covering all other getters available to `Awspec::Type::IAMPolicy`, which should be added using delegation as well.

**Comment by k1LoW** [comment]
@glasswalk3r Thank you 

> That probably should be implemented with method_missing

> Also, I'm not covering all other getters available to Awspec::Type::IAMPolicy, which should be added using delegation as well.

You are right! `Awspec::NoExistingResource` is GOOD !

I think we should implement `Awspec::NoExistingResource` on the parent class not on the `Awspec::Type::IAMPolicy` itself
