### ISSUE TITLE
undefined method `ec2' for main:Object

### ISSUE THREAD

**Issue by jedipunkz** [k1LoW/awspec#92]
I made such spec file named 'test_spec.rb'.

```
describe ec2('test-instance') do
  it { should be_running }
end
```

then I executed 'rake spec', I got error such as.

```
/Users/tomokazu.hirai/Documents/infra_ci/awspec/work/spec/test_spec.rb:8:in `<top (required)>': undefined method `ec2' for main:Object (NoMethodError)
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load'
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `each'
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:41:in `invoke'
        from /Users/tomokazu.hirai/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.1/exe/rspec:4:in `<main>'
```

Any idea do you have ?

**Comment by jedipunkz** [comment]
I used awspec version '0.24.2'

**Comment by k1LoW** [comment]
by any chance

```ruby
require 'spec_helper' # <-

describe ec2('test-instance') do
  it { should be_running }
end
```

**Comment by jedipunkz** [comment]
problem is clear now. thanks.

i think you should add this line (require 'spec_helper') to README.md.

many thanks !

**Comment by k1LoW** [comment]
Added!!

Thank you!

**Comment by sriney-ctp** [comment]
The generate doesn't add the spec_helper require, FYI.
